### ISSUE TITLE
Generate critical css only when ELEVENTY_ENV is for production

### ISSUE THREAD

**Issue by satrya** [gregives/eleventy-critical-css#1]
Hi There,
I am new to Eleventy, and luckily I found this plugin. May I know how to run this plugin only when the environment is for production? I have this under `_data/env.js`

```
module.exports = {
  environment: process.env.ELEVENTY_ENV,
};
```

And this is my npm script
```
"build": "ELEVENTY_ENV=prod run-s build:* postcss",
```

I only want to run this plugin when `ELEVENTY_ENV` is set to `prod`. 

Thank you.

**Comment by gregives** [comment]
Wherever you add the eleventy-critical-css plugin, you can check the environment variable `ELEVENTY_ENV` that you have set in your build script, like so:

```js
module.exports = function (eleventyConfig) {
  if (process.env.ELEVENTY_ENV === "prod") {
    eleventyConfig.addPlugin(require("eleventy-critical-css"));
  }
};
```

**Comment by satrya** [comment]
Hi, yes I was figured it out yesterday. But thanks for your answer
