### ISSUE TITLE
Need help trying to use inline strategy

### ISSUE THREAD

**Issue by ianjmacintosh** [gregives/eleventy-critical-css#4]
I'm trying to use this feature: https://github.com/addyosmani/critical/issues/480#issuecomment-855470176 but I'm not sure how I'd access this "inline strategy" option or if it's not possible without doing some kind of npm dependency magic (my app depends on eleventy-critical-css, which depends on critical, which depends on inline-critical where this feature was added).

If you can help, thanks! If not, thanks for the plugin anyway!

**Comment by gregives** [comment]
Hi @ianjmacintosh, it should work fine without any dependency magic, you can pass options to inline-critical like this:

```js
const criticalCss = require("eleventy-critical-css");

module.exports = (eleventyConfig) => {
  eleventyConfig.addPlugin(criticalCss, {
    inline: {
      strategy: "default",
    },
  });
};

```

Hope that helps!

**Comment by ianjmacintosh** [comment]
> Hi @ianjmacintosh, it should work fine without any dependency magic, you can pass options to inline-critical like this:
> 
> ```js
> const criticalCss = require("eleventy-critical-css");
> 
> module.exports = (eleventyConfig) => {
>   eleventyConfig.addPlugin(criticalCss, {
>     inline: {
>       strategy: "default",
>     },
>   });
> };
> ```
> 
> Hope that helps!

Yep, that worked, thank you. I was using an outdated version of eleventy-critical-css (0.2.4) and just confirmed 1.0.0 supports this behavior. Closing.
